### ISSUE TITLE
请问最近还有更新么，最近包解不了了

### ISSUE THREAD

**Issue by githubxl77** [xuedingmiaojun/wxappUnpacker#10]
wuLib.js:86
        if (err) throw Error("Save file error: " + err);
                 ^

Error: Save file error: Error: ENOENT: no such file or directory, open。。。会出现上述问题请问大佬怎么解决，有偿解决也请报个价，能否加个Q

**Comment by xuedingmiaojun** [comment]
加微信吧xuedingmiaojun





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月15日(星期六) 凌晨3:36
收件人:&nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[xuedingmiaojun/wxappUnpacker] 请问最近还有更新么，最近包解不了了 (#10)





 
wuLib.js:86
 if (err) throw Error("Save file error: " + err);
 ^
 
Error: Save file error: Error: ENOENT: no such file or directory, open。。。会出现上述问题请问大佬怎么解决，有偿解决也请报个价，能否加个Q

**Comment by 15192095633** [comment]
我可以解一下! qq717088069

**Comment by 634739726** [comment]
+1，遇到一样的问题，多少钱可以解决

**Comment by xuedingmiaojun** [comment]
私




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月9日(星期二) 下午3:03
***@***.***&gt;;
抄送:&nbsp;"СЮЭ ***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [xuedingmiaojun/wxappUnpacker] 请问最近还有更新么，最近包解不了了 (#10)





 
+1，遇到一样的问题，多少钱可以解决
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
