### ISSUE TITLE
个别解析路径有问题

### ISSUE THREAD

**Issue by Cherry-toto** [xuedingmiaojun/wxappUnpacker#4]
执行的解析命令如下：
`sh ./bingo.sh C:/Users/Administrator/Desktop/开发相关/xcx/pkg7/_-2100370234_30.wxapkg`

抛出错误：
`
C:\Users\Administrator\Desktop\开发相关\xcx\wxappUnpacker\wuLib.js:86
        if (err) throw Error("Save file error: " + err);
                 ^

Error: Save file error: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Desktop\开发相关\xcx\pkg7\_-2100370234_30\yidu_tc\pages\index\plugin:\wxa75efa648b60994b\video.json'
    at C:\Users\Administrator\Desktop\开发相关\xcx\wxappUnpacker\wuLib.js:86:24
    at agent (C:\Users\Administrator\Desktop\开发相关\xcx\wxappUnpacker\wuLib.js:64:23)
    at fs.js:1262:7
    at FSReqCallback.oncomplete (fs.js:154:23)
`
本地文件对照报错代码如下：wuLib.js:86
`
function save(name, content) {
    ioEvent.encount();
    mkdirs(path.dirname(name), () => ioLimit.runWithCb(fs.writeFile.bind(fs), name, content, err => {
        if (err) throw Error("Save file error: " + err);//此处为86行
        ioEvent.decount();
    }));
}

`

源码包提供：(为了避免被滥用，已取消资源下载)

**Comment by xuedingmiaojun** [comment]
可能是中文路径的问题，我这执行是没问题的&nbsp; Windows 需要使用.bat那个脚本 不想用脚本可以用 另外一个工具&nbsp;https://github.com/xuedingmiaojun/mp-unpack&nbsp; 在release里有打包好的安装包




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月13日(星期一) 中午12:02
收件人:&nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[xuedingmiaojun/wxappUnpacker] 个别解析路径有问题 (#4)





 
执行的解析命令如下：
 sh ./bingo.sh C:/Users/Administrator/Desktop/开发相关/xcx/pkg7/_-2100370234_30.wxapkg
 
抛出错误：
 `
 C:\Users\Administrator\Desktop\开发相关\xcx\wxappUnpacker\wuLib.js:86
 if (err) throw Error("Save file error: " + err);
 ^
 
Error: Save file error: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Desktop\开发相关\xcx\pkg7_-2100370234_30\yidu_tc\pages\index\plugin:\wxa75efa648b60994b\video.json'
 at C:\Users\Administrator\Desktop\开发相关\xcx\wxappUnpacker\wuLib.js:86:24
 at agent (C:\Users\Administrator\Desktop\开发相关\xcx\wxappUnpacker\wuLib.js:64:23)
 at fs.js:1262:7
 at FSReqCallback.oncomplete (fs.js:154:23)
 本地文件对照报错代码如下：wuLib.js:86
 function save(name, content) {
 ioEvent.encount();
 mkdirs(path.dirname(name), () =&gt; ioLimit.runWithCb(fs.writeFile.bind(fs), name, content, err =&gt; {
 if (err) throw Error("Save file error: " + err);//此处为86行
 ioEvent.decount();
 }));
 }
 
`
 
源码包提供：点击下载

**Comment by Cherry-toto** [comment]
> 可能是中文路径的问题，我这执行是没问题的&nbsp; Windows 需要使用.bat那个脚本 不想用脚本可以用 另外一个工具&nbsp;https://github.com/xuedingmiaojun/mp-unpack&nbsp; 在release里有打包好的安装包
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xuedingmiaojun/wxappUnpacker" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月13日(星期一) 中午12:02 收件人:&nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[xuedingmiaojun/wxappUnpacker] 个别解析路径有问题 (#4) 执行的解析命令如下： sh ./bingo.sh C:/Users/Administrator/Desktop/开发相关/xcx/pkg7/_-2100370234_30.wxapkg 抛出错误： ` C:\Users\Administrator\Desktop\开发相关\xcx\wxappUnpacker\wuLib.js:86 if (err) throw Error("Save file error: " + err); ^ Error: Save file error: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Desktop\开发相关\xcx\pkg7_-2100370234_30\yidu_tc\pages\index\plugin:\wxa75efa648b60994b\video.json' at C:\Users\Administrator\Desktop\开发相关\xcx\wxappUnpacker\wuLib.js:86:24 at agent (C:\Users\Administrator\Desktop\开发相关\xcx\wxappUnpacker\wuLib.js:64:23) at fs.js:1262:7 at FSReqCallback.oncomplete (fs.js:154:23) 本地文件对照报错代码如下：wuLib.js:86 function save(name, content) { ioEvent.encount(); mkdirs(path.dirname(name), () =&gt; ioLimit.runWithCb(fs.writeFile.bind(fs), name, content, err =&gt; { if (err) throw Error("Save file error: " + err);//此处为86行 ioEvent.decount(); })); } ` 源码包提供：点击下载 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢解答。我让朋友那边用mac环境试试。

**Comment by xuedingmiaojun** [comment]
上一封的附件_-2100370234_30_unpack.zip是已经解包之后的&nbsp;你可以下下来试试看&nbsp;https://mail.qq.com/cgi-bin/download?mailid=ZL1213-HufJeIpytYiDJDlmTr7ifa7&amp;filename=_-2100370234_30_unpack.zip&amp;sid=4huJ_Qv-z-L5ChdI






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月13日(星期一) 下午2:08
收件人:&nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&gt;;
抄送:&nbsp;"СЮЭ Gang"<490599161@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xuedingmiaojun/wxappUnpacker] 个别解析路径有问题 (#4)





  
可能是中文路径的问题，我这执行是没问题的&nbsp; Windows 需要使用.bat那个脚本 不想用脚本可以用 另外一个工具&nbsp;https://github.com/xuedingmiaojun/mp-unpack&nbsp; 在release里有打包好的安装包
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xuedingmiaojun/wxappUnpacker" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月13日(星期一) 中午12:02 收件人:&nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[xuedingmiaojun/wxappUnpacker] 个别解析路径有问题 (#4) 执行的解析命令如下： sh ./bingo.sh C:/Users/Administrator/Desktop/开发相关/xcx/pkg7/_-2100370234_30.wxapkg 抛出错误： C:\Users\Administrator\Desktop\开发相关\xcx\wxappUnpacker\wuLib.js:86 if (err) throw Error("Save file error: " + err); ^ Error: Save file error: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Desktop\开发相关\xcx\pkg7_-2100370234_30\yidu_tc\pages\index\plugin:\wxa75efa648b60994b\video.json' at C:\Users\Administrator\Desktop\开发相关\xcx\wxappUnpacker\wuLib.js:86:24 at agent (C:\Users\Administrator\Desktop\开发相关\xcx\wxappUnpacker\wuLib.js:64:23) at fs.js:1262:7 at FSReqCallback.oncomplete (fs.js:154:23) 本地文件对照报错代码如下：wuLib.js:86 function save(name, content) { ioEvent.encount(); mkdirs(path.dirname(name), () =&amp;gt; ioLimit.runWithCb(fs.writeFile.bind(fs), name, content, err =&amp;gt; { if (err) throw Error("Save file error: " + err);//此处为86行 ioEvent.decount(); })); } 源码包提供：点击下载 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
感谢解答。我让朋友那边用mac环境试试。

**Comment by Cherry-toto** [comment]
你好，我认真去测试了几次，发现确实是有问题，并不是你说的中文路径问题。我截图给你看



使用您的工具也是会报错的。
错误信息如下：
C:\Users\Administrator\AppData\Local\Programs\mp-unpack\re
sources\tool\wuLib.js:86 if (err) throw Error("Save file error: " + err); ^ Error: Save file error
: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\
Local\Programs\mp-unpack\resources\tool\_
-2100370234_30\yidu_tc\page
s\tabbar\plugin:\wxa75efa648b60994
b\video.json' at C:\Users\Administrat
or\AppData\Local\Programs\mp-unpack\resources\tool
\wuLib.js:86:24 at agent (C:\Users\Administrator\Ap
pData\Local\Programs\mp-unpack\resources\tool\wu
Lib.js:64:23) at fs.js:1262:7 at FSReqCallback.onc
omplete (fs.js:154:23)&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月13日(星期一) 中午1:59
收件人:&nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&gt;;
抄送:&nbsp;"如沐春"<2581047041@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xuedingmiaojun/wxappUnpacker] 个别解析路径有问题 (#4)





 可能是中文路径的问题，我这执行是没问题的&amp;nbsp; Windows 需要使用.bat那个脚本 不想用脚本可以用 另外一个工具&amp;nbsp;https://github.com/xuedingmiaojun/mp-unpack&amp;nbsp; 在release里有打包好的安装包 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年7月13日(星期一) 中午12:02 
 收件人:&amp;nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;[xuedingmiaojun/wxappUnpacker] 个别解析路径有问题 (#4) 
 
 
 
 
 
   
 执行的解析命令如下： 
  sh ./bingo.sh C:/Users/Administrator/Desktop/开发相关/xcx/pkg7/_-2100370234_30.wxapkg 
   
 抛出错误： 
  ` 
  C:\Users\Administrator\Desktop\开发相关\xcx\wxappUnpacker\wuLib.js:86 
  if (err) throw Error("Save file error: " + err); 
  ^ 
   
 Error: Save file error: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Desktop\开发相关\xcx\pkg7_-2100370234_30\yidu_tc\pages\index\plugin:\wxa75efa648b60994b\video.json' 
  at C:\Users\Administrator\Desktop\开发相关\xcx\wxappUnpacker\wuLib.js:86:24 
  at agent (C:\Users\Administrator\Desktop\开发相关\xcx\wxappUnpacker\wuLib.js:64:23) 
  at fs.js:1262:7 
  at FSReqCallback.oncomplete (fs.js:154:23) 
  本地文件对照报错代码如下：wuLib.js:86 
  function save(name, content) { 
  ioEvent.encount(); 
  mkdirs(path.dirname(name), () =&amp;gt; ioLimit.runWithCb(fs.writeFile.bind(fs), name, content, err =&amp;gt; { 
  if (err) throw Error("Save file error: " + err);//此处为86行 
  ioEvent.decount(); 
  })); 
  } 
   
 ` 
   
 源码包提供：点击下载

**Comment by Cherry-toto** [comment]
> 上一封的附件_-2100370234_30_unpack.zip是已经解包之后的&nbsp;你可以下下来试试看&nbsp;https://mail.qq.com/cgi-bin/download?mailid=ZL1213-HufJeIpytYiDJDlmTr7ifa7&amp;filename=_-2100370234_30_unpack.zip&amp;sid=4huJ_Qv-z-L5ChdI
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xuedingmiaojun/wxappUnpacker" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月13日(星期一) 下午2:08 收件人:&nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&gt;; 抄送:&nbsp;"СЮЭ Gang"<490599161@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [xuedingmiaojun/wxappUnpacker] 个别解析路径有问题 (#4) 可能是中文路径的问题，我这执行是没问题的&nbsp; Windows 需要使用.bat那个脚本 不想用脚本可以用 另外一个工具&nbsp;https://github.com/xuedingmiaojun/mp-unpack&nbsp; 在release里有打包好的安装包 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xuedingmiaojun/wxappUnpacker" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月13日(星期一) 中午12:02 收件人:&nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[xuedingmiaojun/wxappUnpacker] 个别解析路径有问题 (#4) 执行的解析命令如下： sh ./bingo.sh C:/Users/Administrator/Desktop/开发相关/xcx/pkg7/_-2100370234_30.wxapkg 抛出错误： C:\Users\Administrator\Desktop\开发相关\xcx\wxappUnpacker\wuLib.js:86 if (err) throw Error("Save file error: " + err); ^ Error: Save file error: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Desktop\开发相关\xcx\pkg7_-2100370234_30\yidu_tc\pages\index\plugin:\wxa75efa648b60994b\video.json' at C:\Users\Administrator\Desktop\开发相关\xcx\wxappUnpacker\wuLib.js:86:24 at agent (C:\Users\Administrator\Desktop\开发相关\xcx\wxappUnpacker\wuLib.js:64:23) at fs.js:1262:7 at FSReqCallback.oncomplete (fs.js:154:23) 本地文件对照报错代码如下：wuLib.js:86 function save(name, content) { ioEvent.encount(); mkdirs(path.dirname(name), () =&amp;gt; ioLimit.runWithCb(fs.writeFile.bind(fs), name, content, err =&amp;gt; { if (err) throw Error("Save file error: " + err);//此处为86行 ioEvent.decount(); })); } 源码包提供：点击下载 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 感谢解答。我让朋友那边用mac环境试试。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

你发的解析压缩包我下载不了。

**Comment by xuedingmiaojun** [comment]
试了下是可以解的 包也放附件了&nbsp; 下载不了吗&nbsp;








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月13日(星期一) 下午2:38
收件人:&nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&gt;;
抄送:&nbsp;"СЮЭ Gang"<490599161@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xuedingmiaojun/wxappUnpacker] 个别解析路径有问题 (#4)





  
上一封的附件_-2100370234_30_unpack.zip是已经解包之后的&nbsp;你可以下下来试试看&nbsp;#
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xuedingmiaojun/wxappUnpacker" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月13日(星期一) 下午2:08 收件人:&nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&gt;; 抄送:&nbsp;"СЮЭ Gang"<490599161@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [xuedingmiaojun/wxappUnpacker] 个别解析路径有问题 (#4) 可能是中文路径的问题，我这执行是没问题的&nbsp; Windows 需要使用.bat那个脚本 不想用脚本可以用 另外一个工具&nbsp;https://github.com/xuedingmiaojun/mp-unpack&nbsp; 在release里有打包好的安装包 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xuedingmiaojun/wxappUnpacker" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月13日(星期一) 中午12:02 收件人:&nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[xuedingmiaojun/wxappUnpacker] 个别解析路径有问题 (#4) 执行的解析命令如下： sh ./bingo.sh C:/Users/Administrator/Desktop/开发相关/xcx/pkg7/-2100370234_30.wxapkg 抛出错误： C:\Users\Administrator\Desktop\开发相关\xcx\wxappUnpacker\wuLib.js:86 if (err) throw Error("Save file error: " + err); ^ Error: Save file error: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Desktop\开发相关\xcx\pkg7-2100370234_30\yidu_tc\pages\index\plugin:\wxa75efa648b60994b\video.json' at C:\Users\Administrator\Desktop\开发相关\xcx\wxappUnpacker\wuLib.js:86:24 at agent (C:\Users\Administrator\Desktop\开发相关\xcx\wxappUnpacker\wuLib.js:64:23) at fs.js:1262:7 at FSReqCallback.oncomplete (fs.js:154:23) 本地文件对照报错代码如下：wuLib.js:86 function save(name, content) { ioEvent.encount(); mkdirs(path.dirname(name), () =&amp;gt; ioLimit.runWithCb(fs.writeFile.bind(fs), name, content, err =&amp;gt; { if (err) throw Error("Save file error: " + err);//此处为86行 ioEvent.decount(); })); } 源码包提供：点击下载 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 感谢解答。我让朋友那边用mac环境试试。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你发的解析压缩包我下载不了。

**Comment by Cherry-toto** [comment]
你发来的包没办法下载。
我本地解析总是报错，我让朋友去解析也是一样
`D:\gitwww\wxappUnpacker\wuLib.js:86
        if (err) throw Error("Save file error: " + err);
                 ^

Error: Save file error: Error: ENOENT: no such file or directory, open 'D:\gitwww\wxappUnpacker\www\_-2100370234_30\yidu_tc\pages\tabbar\plugin:\wxa75efa648b60994b\video.json'
    at D:\gitwww\wxappUnpacker\wuLib.js:86:24
    at agent (D:\gitwww\wxappUnpacker\wuLib.js:64:23)
    at fs.js:1336:7
    at FSReqCallback.oncomplete (fs.js:155:23)
`
麻烦你看下解析出来的文件，里面的文件是否正常解析

**Comment by xuedingmiaojun** [comment]
解包之后的放微云里了，可以下载看一下，https://share.weiyun.com/PI3n6srZ




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月13日(星期一) 晚上7:46
收件人:&nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&gt;;
抄送:&nbsp;"СЮЭ Gang"<490599161@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xuedingmiaojun/wxappUnpacker] 个别解析路径有问题 (#4)





 
你发来的包没办法下载。
 我本地解析总是报错，我让朋友去解析也是一样
 `D:\gitwww\wxappUnpacker\wuLib.js:86
 if (err) throw Error("Save file error: " + err);
 ^
 
Error: Save file error: Error: ENOENT: no such file or directory, open 'D:\gitwww\wxappUnpacker\www_-2100370234_30\yidu_tc\pages\tabbar\plugin:\wxa75efa648b60994b\video.json'
 at D:\gitwww\wxappUnpacker\wuLib.js:86:24
 at agent (D:\gitwww\wxappUnpacker\wuLib.js:64:23)
 at fs.js:1336:7
 at FSReqCallback.oncomplete (fs.js:155:23)
 `
 麻烦你看下解析出来的文件，里面的文件是否正常解析

**Comment by Cherry-toto** [comment]
> 解包之后的放微云里了，可以下载看一下，https://share.weiyun.com/PI3n6srZ
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xuedingmiaojun/wxappUnpacker" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月13日(星期一) 晚上7:46 收件人:&nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&gt;; 抄送:&nbsp;"СЮЭ Gang"<490599161@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [xuedingmiaojun/wxappUnpacker] 个别解析路径有问题 (#4) 你发来的包没办法下载。 我本地解析总是报错，我让朋友去解析也是一样 `D:\gitwww\wxappUnpacker\wuLib.js:86 if (err) throw Error("Save file error: " + err); ^ Error: Save file error: Error: ENOENT: no such file or directory, open 'D:\gitwww\wxappUnpacker\www_-2100370234_30\yidu_tc\pages\tabbar\plugin:\wxa75efa648b60994b\video.json' at D:\gitwww\wxappUnpacker\wuLib.js:86:24 at agent (D:\gitwww\wxappUnpacker\wuLib.js:64:23) at fs.js:1336:7 at FSReqCallback.oncomplete (fs.js:155:23) ` 麻烦你看下解析出来的文件，里面的文件是否正常解析 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

您发的包好像解析的不错，不过我还是有疑问，你的为啥能解析。。。主要还是我不太懂js，只要排除掉那个冒号的文件目录应该就能解析。抱歉打扰了。谢谢解答
